from collections.abc import Iterator

__all__ = ['first_common_ancestor', 'iterate_over_arguments']

def first_common_ancestor(cls1: type, cls2: type) -> type: ...
def iterate_over_arguments[A](*args: A) -> Iterator[A]: ...
