__all__ = ['NoValue']

class NoValue:
    def __new__(cls) -> NoValue: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
